# ==============================================================
# PERFIL: DEV  (localhost + Mailtrap)
# ==============================================================

# --- Base de datos ---
spring.datasource.url=jdbc:mysql://localhost:3306/nutripharma_v2?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Correo (RESEND - DEV) ---
spring.mail.host=smtp.resend.com
spring.mail.port=587
spring.mail.username=resend
spring.mail.password=${RESEND_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.resend.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

# --- Frontend URL ---
app.frontend.url=http://localhost:5173

# --- JWT ---
security.jwt.secret-key=${JWT_SECRET}

# --- Google Drive ---
google.drive.folder.id=${GOOGLE_FOLDER_ID}
google.drive.client.id=${GOOGLE_CLIENT_ID}
google.drive.client.secret=${GOOGLE_CLIENT_SECRET}
google.drive.refresh.token=${GOOGLE_REFRESH_TOKEN}
